# Use an official Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the script into the container
COPY app.py .

ENV NAME=Bob

# Set the default command
CMD ["python", "app.py"]
